### ISSUE TITLE
如何让你一个img在div里居中？

### ISSUE THREAD

**Issue by renhaojiecode** [renhaojiecode/demo#2]
常用的display:table-cell; 就不介绍了 不兼容ie6/7  
定位也不多说今天介绍几个不常用的方法 

### 1、使用一个空的span做基线
```css
div{ width:300px; height:300px; border:1px solid red; margin:0 auto; text-align:center; }
img{ vertical-align:middle;}
span{ height:100%; display:inline-block; vertical-align:middle;}
```
```html
<div>
    	<img src="a.jpg" />
        <span></span><!--基线-->
</div>
```
### 2、使用line-height  和 vertical-align
```css
div{ width:500px; height: 500px; border:1px solid red; text-align: center; line-height: 500px; float:left; font-size:0;}
img{ vertical-align:middle;}
```
```html
<div class="img1">
        <img src="a.jpg" alt="">
</div>
```
